apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: 610595224833.dkr.ecr.us-east-1.amazonaws.com/restaurant-service:latest
          ports:
            - containerPort: 8002
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb-service:27017"
            - name: SECRET_KEY
              value: "some_very_long_random_string_at_least_32_chars"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:29092"
          envFrom:
            - secretRef:
                name: aws-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP